[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "soilspectfm"
dynamic = ["version"]
description = "Scikit-learn transformers for preprocessing soil infrared spectra"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
authors = [{name = "Franck Albinet", email = "franckalbinet@gmail.com"}]
keywords = ['soil', 'spectroscopy', 'infrared', 'chemometrics', 'scikit-learn', 'preprocessing']
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"]
dependencies = ['fastcore', 'scikit-learn', 'matplotlib', 'PyWavelets', 'numpy', 'scipy', 'pandas']

[project.urls]
Repository = "https://github.com/franckalbinet/soilspectfm"
Documentation = "https://franckalbinet.github.io/soilspectfm"

[project.entry-points.nbdev]
soilspectfm = "soilspectfm._modidx:d"

[project.optional-dependencies]
dev = ['soilspecdata>=0.2', 'nbdev', 'ipykernel', 'twine']

[tool.setuptools.dynamic]
version = {attr = "soilspectfm.__version__"}

[tool.setuptools.packages.find]
include = ["soilspectfm*"]

[tool.setuptools.package-data]
soilspectfm = ["data/*.csv.gz"]

[tool.nbdev]
custom_sidebar = true
title = 'SoilSpecTfm'
