# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/soilspectfm',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/soilspectfm',
                'lib_path': 'soilspectfm'},
  'syms': {'soilspectfm.core': {'soilspectfm.core.foo': ('core.html#foo', 'soilspectfm/core.py')}}}
