"""Scikit-learn transformers for preprocessing soil spectra

Docs: https://franckalbinet.github.io/soilspectfm/preprocessing.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_preprocessing.ipynb.

# %% auto #0
__all__ = ['SNV', 'MSC', 'SavitzkyGolay', 'WaveletDenoise', 'ToAbsorbance', 'Resample', 'Trim']

# %% ../nbs/00_preprocessing.ipynb #2ad78b86
from fastcore.all import *
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.utils.validation import check_is_fitted
from scipy.signal import savgol_filter
from scipy.interpolate import make_interp_spline
from typing import Callable
import pywt

# %% ../nbs/00_preprocessing.ipynb #5a48b646
class SNV(BaseEstimator, TransformerMixin):
    "Center and scale each spectrum independently (Standard Normal Variate)"
    def __init__(self,
        center_func: Callable=np.mean, # Function to center the data
        scale_func: Callable=np.std, # Function to scale the data
        eps: float=1e-10 # Small value to avoid division by zero
    ):
        store_attr()
    def fit(self, X, y=None): return self
    def transform(self,
        X: np.ndarray # Spectral data to be transformed
    ) -> np.ndarray: # Transformed spectra
        center = self.center_func(X, axis=1, keepdims=True)
        scale = self.scale_func(X - center, axis=1, keepdims=True) + self.eps
        return (X - center) / scale

# %% ../nbs/00_preprocessing.ipynb #cd432c71
class MSC(BaseEstimator, TransformerMixin):
    "Multiplicative Scatter Correction against a reference spectrum"
    def __init__(self,
        reference_method: Union[str, np.ndarray] = 'mean', # 'mean', 'median', or a reference spectrum
    ):
        store_attr()
        
    def _compute_reference(self, x: np.ndarray):
        "Compute reference spectrum from array using specified method"
        if isinstance(self.reference_method, str):
            if self.reference_method not in ('mean', 'median'): raise ValueError("reference_method must be 'mean', 'median' or a spectrum")
            return np.mean(x, axis=0) if self.reference_method == 'mean' else np.median(x, axis=0)
        return np.array(self.reference_method)
    
    def fit(self, X: np.ndarray, y=None):
        "Compute the reference spectrum"
        self.reference_ = self._compute_reference(X)
        return self
    
    def transform(self,
        X: np.ndarray # Spectral data to be transformed
    ) -> np.ndarray: # Transformed spectra
        "Apply MSC to the spectra"
        check_is_fitted(self)
        X = np.asarray(X)
        slope, intercept = np.polyfit(self.reference_, X.T, deg=1)
        return (X - intercept[:, None]) / slope[:, None]

# %% ../nbs/00_preprocessing.ipynb #1e1f8cee
class SavitzkyGolay(BaseEstimator, TransformerMixin):
    "Savitzky-Golay smoothing or derivative of each spectrum"
    def __init__(self,
        window_length:int=15, # Number of points in each filter window, odd
        polyorder:int=3, # Degree of the polynomial fitted in each window
        deriv:int=0 # Derivative order, 0 to smooth only
    ): store_attr()

    def fit(self,
        X:np.ndarray, # Spectra, one per row
        y:np.ndarray=None # Ignored
    ):
        "Check that the filter parameters are consistent"
        if self.window_length % 2 == 0: raise ValueError("window_length must be odd")
        if self.window_length <= self.polyorder: raise ValueError("window_length must be greater than polyorder")
        if self.deriv > self.polyorder: raise ValueError("deriv must be <= polyorder")
        return self

    def transform(self,
        X:np.ndarray # Spectra, one per row
    ) -> np.ndarray: # Filtered spectra
        "Filter each spectrum"
        return savgol_filter(np.asarray(X), self.window_length, self.polyorder, self.deriv)

# %% ../nbs/00_preprocessing.ipynb #f6cf2e8e
class WaveletDenoise(BaseEstimator, TransformerMixin):
    "Wavelet denoising of each spectrum"
    def __init__(self,
        wavelet:str='db6', # Wavelet to use for decomposition
        level:Optional[int]=None, # Decomposition level. If None, maximum level is used
        threshold_mode:str='soft' # Thresholding mode, 'soft' or 'hard'
    ):
        store_attr()
        
    def _denoise_single(self, spectrum):
        "Denoise a single spectrum"
        coeffs = pywt.wavedec(spectrum, self.wavelet, level=self.level_)
        
        detail_coeffs = np.concatenate(coeffs[1:])
        sigma = np.median(np.abs(detail_coeffs)) / 0.6745
        threshold = sigma * np.sqrt(2 * np.log(len(spectrum)))
        
        new_coeffs = list(coeffs)
        for i in range(1, len(coeffs)):
            new_coeffs[i] = pywt.threshold(coeffs[i], threshold * (1 / 2 ** ((self.level_ - i) / 2)), mode=self.threshold_mode)

        denoised = pywt.waverec(new_coeffs, self.wavelet)
        return denoised[:len(spectrum)]
    
    def fit(self, X, y=None):
        "Set `level_`: `level`, or the deepest level the spectrum length allows"
        self.level_ = ifnone(self.level, pywt.dwt_max_level(np.shape(X)[1], pywt.Wavelet(self.wavelet).dec_len))
        return self
    
    def transform(self, X):
        "Denoise each spectrum"
        X = np.asarray(X)
        X_denoised = np.zeros_like(X)
        for i in range(X.shape[0]): X_denoised[i] = self._denoise_single(X[i])
        return X_denoised

# %% ../nbs/00_preprocessing.ipynb #a9a01eb8
class ToAbsorbance(BaseEstimator, TransformerMixin):
    "Convert reflectance to absorbance, `-log10(R)`"
    def __init__(self,
        eps: float=1e-5 # Small value to avoid log(0)
    ): self.eps = eps
    def fit(self, X, y=None): return self
    def transform(self, X, y=None): return -np.log10(np.clip(X, self.eps, 1))

# %% ../nbs/00_preprocessing.ipynb #98f442b8
class Resample(BaseEstimator, TransformerMixin):
    "Resample spectra onto new x-axis points by spline interpolation"
    def __init__(self,
        source_x: np.ndarray, # Source x-axis points (wavenumbers or wavelengths)
        target_x: np.ndarray, # Target x-axis points (wavenumbers or wavelengths) for resampling
        interpolation_kind: str='cubic' # Spline kind: 'linear', 'quadratic' or 'cubic'
    ):
        store_attr()
        
    def fit(self,
        X: np.ndarray, # Spectral data to be resampled
        y: np.ndarray=None # Ignored
    ):
        "Check `X` against `source_x`, check `target_x` is in range, and sort `source_x`"
        n_cols, n_src = np.shape(X)[1], len(self.source_x)
        if n_cols != n_src: raise ValueError(f"X has {n_cols} columns but source_x has {n_src} points")
        self.order_ = np.argsort(self.source_x)
        lo, hi = np.asarray(self.source_x)[self.order_[[0, -1]]]
        if np.min(self.target_x) < lo or np.max(self.target_x) > hi:
            raise ValueError(f"target_x must lie within the source_x range [{lo}, {hi}]")
        return self
    
    def transform(self,
        X: np.ndarray # Spectral data to be resampled
    ):
        "Interpolate each spectrum at `target_x`"
        k = dict(linear=1, quadratic=2, cubic=3)[self.interpolation_kind]
        xs = np.asarray(self.source_x)[self.order_]
        return make_interp_spline(xs, np.asarray(X)[:, self.order_], k=k, axis=1)(self.target_x)

# %% ../nbs/00_preprocessing.ipynb #88222cd5
class Trim(BaseEstimator, TransformerMixin):
    "Keep the wavenumbers (or wavelengths) between `w_min` and `w_max`"
    def __init__(self,
        ws: np.ndarray, # Wavenumbers or wavelengths
        w_min: Optional[float]=None, # Minimum wavenumber or wavelength
        w_max: Optional[float]=None # Maximum wavenumber or wavelength
    ):
        store_attr()
        
    def fit(self,
        X: np.ndarray, # Spectra to be trimmed
        y: Optional[np.ndarray]=None # Ignored
    ):
        "Compute `mask_`, the columns whose wavenumber is inside the range"
        self.mask_ = (self.ws >= (-np.inf if self.w_min is None else self.w_min)) & \
                     (self.ws <= (np.inf if self.w_max is None else self.w_max))
        return self
    
    def transform(self, X: np.ndarray) -> np.ndarray:
        "Keep the columns inside the range"
        return X[:, self.mask_]
    
    def get_wavenumbers(self) -> np.ndarray:
        "Return the trimmed wavenumbers"
        return self.ws[self.mask_]
